### ISSUE TITLE
Chapter 10: WASM samples not working (issue)

### ISSUE THREAD

**Issue by ClimberBear** [PacktPublishing/Web-Development-with-Blazor-Third-Edition#17]
I have open [this issue](https://stackoverflow.com/questions/78626133/blazor-wasm-system-runtime-interopservices-javascript-is-not-supported-on-this) in StackOverflow.

I'm not sure if this is a problem with the book code or with my platform.

Could you take a look? 

Thank you very much in advance!!!

**Comment by EngstromJimmy** [comment]
I haven't looked at it yet (I am not close to a computer)
The JSImport and JSExport functions needs to run on WebAssembly.
Try and run the project in a Blazor WebAssembly Standalone project and see if there is a change.
Not sure right now if it works if you are running the Web App Template.

**Comment by ClimberBear** [comment]
Hi

Thank you for answer so quick!

It “smell” like a very well known issue, but I’m not able to find the relevant docs:


  *   If I test the official sample in BlazorSample_WebAssembly<https://github.com/dotnet/blazor-samples/tree/31b59a54a172a3ee18dde49dbbea83e41ca8e757/8.0/BlazorSample_WebAssembly>, I get the following
     *   Same error when I try to debug with VSCode in Mac
     *   But it runs smooth if run directly with dotnet run
  *   But my sample fails with the same error in debug or publish mode

So, I imagine that the problem is the debug mode in Mac, and the official samples workaround this in some way (but I’m not sure)


Jose M. Albarrán
Tlfo: +34 616 968 262
e-Mail: ***@***.******@***.***>
LinkedIn: https://es.linkedin.com/in/jmalbarran
Also available in Telegram, Signal, Skype (jmalbarran). I don't use WhatsApp.


De: Jimmy Engstrom ***@***.***>
Fecha: sábado, 15 de junio de 2024, 12:59
Para: PacktPublishing/Web-Development-with-Blazor-Third-Edition ***@***.***>
CC: Jose Manuel Albarrán ***@***.***>, Author ***@***.***>
Asunto: Re: [PacktPublishing/Web-Development-with-Blazor-Third-Edition] Chapter 10: WASM samples not working (issue) (Issue #17)

I haven't looked at it yet (I am not close to a computer)
The JSImport and JSExport functions needs to run on WebAssembly.
Try and run the project in a Blazor WebAssembly Standalone project and see if there is a change.
Not sure right now if it works if you are running the Web App Template.

**Comment by ClimberBear** [comment]
Additionally, this chapter is really confusing, because the code in the book seems to be created for a specific solution `BlazorWebAssembly`, with specific project `BlazorWebAssembly.Client`, but the code in the repository is based in the previous `SharedComponents` project.

**Comment by ClimberBear** [comment]
Hi

I found the issue. I had to deactivate the prerender mode as `@rendermode @(new InteractiveWebAssemblyRenderMode(prerender:false))`
