### ISSUE TITLE
Ch 6 - Page 119 - Getting 2 errors compiling project SharedComponents

### ISSUE THREAD

**Issue by SurajKapadia** [PacktPublishing/Web-Development-with-Blazor-Third-Edition#19]
File - Chapter06/MyBlog/SharedComponents/Pages/Admin/CategoryList.razor
Page 119 - Step 6.

Line 17 - `<ItemList Items="Items" DeleteEvent="@Delete" SelectEvent="@Select" ItemType="Category">`
Code: CS1503
Description: Argument 2: cannot convert from 'method group' to 'Microsoft.AspNetCore.Components.EventCallback'.

Line 20 - `var item = context as Category;`
Code: CS0103
Description: The name 'context' does not exist in the current context.

Please let me know I if missed typing any code that is generating the above errors.
Thanks.

**Comment by EngstromJimmy** [comment]
Hi =)
It looks like you are running the source code from this repo from your message.
The most common reason for that type of error to happen is that the ItemType is not set and Blazor can't figure out what type it is. But from the code you have provided, it seems like you have done that.

However if you are at Step 6, you need to complete 7 and 8 as well before you can expect the code to compile.

**Comment by SurajKapadia** [comment]
Hello Jimmy,

Thank you for prompt reply.  It was my typo.  I did not realize it before posting here.

`ItenType="Category"`

Instead of "**m**", I had typed "**n**" and this caused all the error.
I will mark this issue as closed.

Thanks again.

**Comment by SurajKapadia** [comment]
mark as close.
