### ISSUE TITLE
Chapter 8 - Setting up authentication - page 167

### ISSUE THREAD

**Issue by pmarangoni** [PacktPublishing/Web-Development-with-Blazor-Third-Edition#28]
Trying to get this Auth0 nonsense setup. Your instructions don't match the actual site itself.
I assume that the Application Login URI value is set under the Advanced tab until Tenant Settings, but I'm not sure.
When I try to enter the values you suggest, I get an error.
![Screenshot 2024-07-24 125318](https://github.com/user-attachments/assets/d1c946ad-1654-4139-8f88-e92750ccc4dc)

This is the error when I try to save:
![Screenshot 2024-07-24 125520](https://github.com/user-attachments/assets/7491982b-da2c-4ce1-a922-2534626c04b7)

**Comment by pmarangoni** [comment]
From Auth0:

> The login_url should point to a route in the application that ends up redirecting to Auth0's /authorize endpoint, e.g. https://mycompany.org/login. Note that it requires https and it cannot point to localhost. login_url can include query parameters and a URI fragment.

**Comment by EngstromJimmy** [comment]
You seem to be managing the tenent settings, this is in the application settings.
The book Is referring to the tab "Settings", not the menu item to the left.
Hope that helps =)
