### ISSUE TITLE
Ch 3 - Page 50 - SQL Server example

### ISSUE THREAD

**Issue by SurajKapadia** [PacktPublishing/Web-Development-with-Blazor-Third-Edition#38]
Hello Jimmy,

I could not find example showing SQL Server connection, and CRUD with SQL Server.
Please inform where is the sample on GitHub for SQL Server.

Thanks,
Suraj Kapadia.

**Comment by EngstromJimmy** [comment]
Here it is :) 

https://github.com/PacktPublishing/Web-Development-with-Blazor-Third-Edition/tree/main/Chapter03/MyBlog/EntityFramework
