### ISSUE TITLE
File not found: WeatherCodeBehind.razor.cs 

### ISSUE THREAD

**Issue by ClimberBear** [PacktPublishing/Web-Development-with-Blazor-Third-Edition#8]
The book, in chapter 04, indicate the file `WeatherCodeBehind.razor.cs`as a sample of code-behind. But I'm not able to find neither the file neither the `Examples` folder

**Comment by EngstromJimmy** [comment]
It is this one:

https://github.com/PacktPublishing/Web-Development-with-Blazor-Third-Edition/blob/main/Chapter04/MyBlog/Examples/WeatherWithCodeBehind.razor.cs

**Comment by ClimberBear** [comment]
Thanks! I'm blind!

Enviado desde Outlook para Android<https://aka.ms/AAb9ysg>
________________________________
